module.exports = {
  extends: [
    'eslint:recommended',
    'airbnb-typescript/base',
    'plugin:jest/recommended',
    'plugin:@typescript-eslint/recommended',
    'plugin:eslint-comments/recommended',
  ],
  rules: {
    '@typescript-eslint/consistent-type-definitions': ['error', 'interface'],
    '@typescript-eslint/explicit-function-return-type': ['off'],
    '@typescript-eslint/explicit-module-boundary-types': 'off',
    '@typescript-eslint/lines-between-class-members': 'off',
    '@typescript-eslint/no-floating-promises': ['error'],
    '@typescript-eslint/no-unused-vars': ['warn'],
    'no-use-before-define': 'off',
    '@typescript-eslint/no-use-before-define': 'off',
    '@typescript-eslint/no-unnecessary-type-assertion': 'warn',
    complexity: ['error', 6],
    'import/no-extraneous-dependencies': 'off',
    'import/order': [
      'warn',
      {
        groups: [['external', 'builtin']],
        'newlines-between': 'always',
        alphabetize: { order: 'asc' },
      },
    ],
    'import/prefer-default-export': 'off',
    'jest/expect-expect': 'off',
    'jest/valid-title': 'off',
    'max-params': ['error', 3],
    'no-await-in-loop': 'off',
    'no-console': ['warn'],
    'no-implicit-coercion': 'error',
    'no-import-assign': 'error',
    'no-loss-of-precision': 'error',
    'no-param-reassign': ['error', { props: false }],
    'no-restricted-syntax': 'off',
    'no-setter-return': 'error',
    'no-template-curly-in-string': 'off',
    'no-unsafe-optional-chaining': 'error',
    'no-unused-vars': 'off',
    'prettier/prettier': ['warn'],
    'require-await': 'error',
    curly: ['error', 'all'],
  },
  overrides: [
    {
      files: ['*.test.ts'],
      rules: {
        '@typescript-eslint/no-non-null-assertion': 'off',
      },
    },
  ],
};
